Upgrade to 2.4.0-dev.13
camptocamp/demo_geomapfish pull request #99
Opened 2019-01-11 16:18 UTC by fredj

2019-01-11 17:16 UTC, sbrunner requested changes

2019-01-11 17:16 UTC, sbrunner commented on print/print-apps/demo/config.yaml.tmpl
> +              - !acceptAll {}
Many changes in this file are wrong :-(

2019-01-14 09:01 UTC, fredj commented on print/print-apps/demo/config.yaml.tmpl
> +              - !acceptAll {}
see b5c1151

2019-01-14 09:23 UTC, sbrunner approved these changes
Thanks :-)

2019-01-14 09:30 UTC, merged